# Generated by Django 3.2.5 on 2021-07-26 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catagorie', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCatagories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subCatagories', models.CharField(max_length=100, null=True)),
                ('catagorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_india_app.catagories')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('products', models.CharField(max_length=100, null=True)),
                ('subCatagories', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='master_india_app.subcatagories')),
            ],
        ),
    ]
