# Generated by Django 3.2.5 on 2021-07-26 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('master_india_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='subCatagories',
            new_name='subCatagories_obj',
        ),
        migrations.RenameField(
            model_name='subcatagories',
            old_name='catagorie',
            new_name='catagorie_obj',
        ),
    ]
